---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---
```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges()
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## What's Inside The Tin

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r lib-ex}
library(rradar)

# current version
packageVersion("rradar")

```

### Stations

```{r stations}
library(tidyverse)

filter(stations, state == "Maine")

filter(stations, state == "California")
```

```{r right-coast, cache=TRUE}
animate_radar("GYX")
```

```{r left-coast, cache=TRUE}
animate_radar("VBX")
```

```{r mosaic, cache=TRUE}
animate_conus_mosaic("small")
```

```{r stars, fig.width=800/96, fig.height=800/96, cache=TRUE}
library(sf)
library(stars)
library(rradar)
library(viridis)
library(rnaturalearth)
library(hrbrthemes)
library(tidyverse)

wrld <- ne_countries(scale = "medium", country = c("united states of america", "canada"), 
                     continent = "north america", returnclass = "sf")
us <- ne_states("united states of america", returnclass = "sf")

ne_radar <- latest_radar("northeast")

wrld <- st_crop(wrld, st_bbox(ne_radar))
us <- st_crop(us, st_bbox(ne_radar))

ggplot() +
  geom_sf(data = wrld, size = 0.125, fill = '#fefefe') +
  geom_sf(data = us, size = 0.125, fill = '#fefefe') +
  geom_stars(data = ne_radar) +
  coord_sf(datum = NA) +
  scale_fill_rradar() +
  labs(
    x = NULL, y = NULL,
    title = "NWS Radar Mosaic — Northeast Sector",
    subtitle = "1758 UTC 2019-12-15"
  ) +
  theme_ipsum_es(grid="") +
  theme(legend.key.height = unit(5, "lines"))
```

## rradar Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```

## Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. 
By participating in this project you agree to abide by its terms.
