#' NOAA U.S. Radar Stations
#'
#' @docType data
#' @export
structure(list(state = c("Alabama", "Alabama", "Alabama", "Alabama",
"Alabama", "Alaska", "Alaska", "Alaska", "Alaska", "Alaska",
"Alaska", "Alaska", "Alaska", "Alaska", "Arizona", "Arizona",
"Arizona", "Arizona", "Arkansas", "Arkansas", "California", "California",
"California", "California", "California", "California", "California",
"California", "California", "California", "California", "Colorado",
"Colorado", "Colorado", "Delaware", "Florida", "Florida", "Florida",
"Florida", "Florida", "Florida", "Florida", "Florida", "Georgia",
"Georgia", "Georgia", "Georgia", "Guam", "Hawaii", "Hawaii",
"Hawaii", "Hawaii", "Idaho", "Idaho", "Illinois", "Illinois",
"Indiana", "Indiana", "Indiana", "Iowa", "Iowa", "Kansas", "Kansas",
"Kansas", "Kansas", "Kentucky", "Kentucky", "Kentucky", "Kentucky",
"Louisiana", "Louisiana", "Louisiana", "Louisiana", "Maine",
"Maine", "Maryland", "Massachusetts", "Michigan", "Michigan",
"Michigan", "Michigan", "Minnesota", "Minnesota", "Mississippi",
"Mississippi", "Missouri", "Missouri", "Missouri", "Montana",
"Montana", "Montana", "Montana", "Nebraska", "Nebraska", "Nebraska",
"Nevada", "Nevada", "Nevada", "New Jersey", "New Mexico", "New Mexico",
"New Mexico", "New York", "New York", "New York", "New York",
"New York", "New York", "North Carolina", "North Carolina", "North Carolina",
"North Carolina", "North Dakota", "North Dakota", "North Dakota",
"Ohio", "Ohio", "Ohio", "Ohio", "Oklahoma", "Oklahoma", "Oklahoma",
"Oklahoma", "Oregon", "Oregon", "Oregon", "Pennsylvania", "Pennsylvania",
"Pennsylvania", "Puerto Rico", "South Carolina", "South Carolina",
"South Carolina", "South Carolina", "South Carolina", "South Dakota",
"South Dakota", "South Dakota", "Tennessee", "Tennessee", "Tennessee",
"Tennessee", "Tennessee", "Texas", "Texas", "Texas", "Texas",
"Texas", "Texas", "Texas", "Texas", "Texas", "Texas", "Texas",
"Texas", "Texas", "Texas", "Texas", "Texas", "Utah", "Utah",
"Vermont", "Virginia", "Virginia", "Virginia", "Virginia", "Virginia",
"Virginia", "Washington", "Washington", "Washington", "Washington",
"Washington DC", "West Virginia", "Wisconsin", "Wisconsin", "Wisconsin",
"Wyoming", "Wyoming"), city = c("Birmingham", "E. Alabama", "Fort Rucker",
"Mobile", "Nrn. Alabama", "Bethel", "Biorka Is.", "Fairbanks",
"Kenai", "King Salmon", "Middleton Is.", "Nome", "Pedro Dome",
"Sitka", "Flagstaff", "Phoenix", "Tucson", "Yuma", "Little Rock",
"W. Ark./Ft. Smith", "Beale AFB", "Edwards AFB", "Eureka", "Hanford",
"Los Angeles", "Sacramento", "San Diego", "San Francisco", "San Joaquin Vly.",
"Santa Ana Mtns", "Vandenberg AFB", "Denver/Boulder", "Grand Junction",
"Pueblo", "Dover AFB", "Eglin AFB", "Jacksonville", "Key West",
"Melbourne", "Miami", "NW Florida", "Tallahassee", "Tampa Bay Area",
"Atlanta", "Moody AFB", "Peachtree City", "Robins AFB", "Andersen AFB",
"Kauai", "Kohala", "Molokai", "South Shore", "Boise", "Pocatello",
"Central IL", "Chicago", "Evansville", "Indianapolis", "Nrn. Indiana",
"Des Moines", "Quad Cities", "Dodge City", "Goodland", "Topeka",
"Wichita", "Fort Cambell", "Jackson", "Louisville", "Paducah",
"Fort Polk", "Lake Charles", "New Orleans", "Shreveport", "Caribou",
"Portland", "Baltimore", "Boston", "Detroit", "Gaylord", "Grand Rapids",
"Marquette", "Duluth", "Minneapolis", "Columbus AFB", "Jackson/Brandon",
"Kansas City", "Springfield", "St. Louis", "Billings", "Glasgow",
"Great Falls", "Missoula", "Hastings", "North Platte", "Omaha",
"Elko", "Las Vegas", "Reno", "Mt. Holly", "Albuquerque", "Cannon AFB",
"Holloman AFB", "Albany", "Binghamton", "Buffalo", "Montague",
"New York City", "Upton", "Durham", "Morehead City", "Raleigh",
"Wilmington", "Bismarck", "Grand Forks", "Minot AFB", "Cincinnati",
"Cleveland", "Dayton", "Wilmington", "Frederick", "Oklahoma City",
"Tulsa", "Vance AFB", "Medford", "Pendleton", "Portland", "Philadelphia",
"Pittsburgh", "State College", "Puerto Rico/V.I.", "Charleston",
"Columbia", "Greenville", "Spartanburg", "Greer", "Aberdeen",
"Rapid City", "Sioux falls", "Knoxville", "Memphis", "Morristown",
"Nashville", "Tri Cities", "Amarillo", "Austin", "Brownsville",
"Central Texas", "Corpus Christi", "Dallas", "Dyess AFB", "El Paso",
"Fort Worth", "Galveston", "Houston", "Laughlin AFB", "Lubbock",
"Midland/Odessa", "San Angelo", "San Antonio", "Cedar City",
"Salt Lake City", "Burlington", "Blacksburg", "Norfolk", "Richmond",
"Roanoke", "Sterling", "Wakefield", "Langley Hill", "Seattle",
"Spokane", "Tacoma", "Washington", "Charleston", "Green Bay",
"La Crosse", "Milwaukee", "Cheyenne", "Riverton"), dir = c("N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R",
"N0R", "N0R", "N0R", "N0R", "N0R", "N0R", "N0R"), station = c("BMX",
"MXX", "EOX", "MOB", "HTX", "ABC", "ACG", "APD", "AHG", "AKC",
"AIH", "AEC", "APD", "ACG", "FSX", "IWA", "EMX", "YUX", "LZK",
"SRX", "BBX", "EYX", "BHX", "HNX", "VTX", "DAX", "NKX", "MUX",
"HNX", "SOX", "VBX", "FTG", "GJX", "PUX", "DOX", "EVX", "JAX",
"BYX", "MLB", "AMX", "EVX", "TLH", "TBW", "FFC", "VAX", "FFC",
"JGX", "GUA", "HKI", "HKM", "HMO", "HWA", "CBX", "SFX", "ILX",
"LOT", "VWX", "IND", "IWX", "DMX", "DVN", "DDC", "GLD", "TWX",
"ICT", "HPX", "JKL", "LVX", "PAH", "POE", "LCH", "LIX", "SHV",
"CBW", "GYX", "LWX", "BOX", "DTX", "APX", "GRR", "MQT", "DLH",
"MPX", "GWX", "DGX", "EAX", "SGF", "LSX", "BLX", "GGW", "TFX",
"MSX", "UEX", "LNX", "OAX", "LRX", "ESX", "RGX", "DIX", "ABX",
"FDX", "HDX", "ENX", "BGM", "BUF", "TYX", "OKX", "OKX", "RAX",
"MHX", "RAX", "LTX", "BIS", "MVX", "MBX", "ILN", "CLE", "ILN",
"ILN", "FDR", "TLX", "INX", "VNX", "MAX", "PDT", "RTX", "DIX",
"PBZ", "CCX", "JUA", "CLX", "CAE", "GSP", "GSP", "GSP", "ABR",
"UDX", "FSD", "MRX", "NQA", "MRX", "OHX", "MRX", "AMA", "EWX",
"BRO", "GRK", "CRP", "FWS", "DYX", "EPZ", "FWS", "HGX", "HGX",
"DFX", "LBB", "MAF", "SJT", "EWX", "ICX", "MTX", "CXX", "FCX",
"AKQ", "AKQ", "FCX", "LWX", "AKQ", "LGX", "ATX", "OTX", "ATX",
"LWX", "RLX", "GRB", "ARX", "MKX", "CYS", "RIW")), row.names = c(NA,
-179L), class = c("tbl_df", "tbl", "data.frame")) -> stations